name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What is the problem or opportunity?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: extra
    attributes:
      label: Additional context
